# Data Manipulation by selecting rows and cols

## Selecting Columns and Rows

In [1]:
import pandas as pd
import numpy as np

In [89]:
data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohan"],
    "Age": [25, 28, 24, 30, 26],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [45000, 50000, 40000, 60000, 48000]
}

df = pd.DataFrame(data)

## Select a single/multiple column

In [46]:
# Selecting a single columns
df["Name"]
# Selecting multiple columns
df[["Name","Age","Salary"]]

    Name  Age  Salary
0  Rahul   25   45000
1  Priya   28   50000
2   Amit   24   40000
3   Neha   30   60000
4  Rohan   26   48000

## Creating a new Column

In [91]:
df["Bonus"] = df['Salary'] * .1
print(df)

    Name  Age Department  Salary   Bonus
0  Rahul   25         IT   45000  4500.0
1  Priya   28         HR   50000  5000.0
2   Amit   24         IT   40000  4000.0
3   Neha   30    Finance   60000  6000.0
4  Rohan   26         HR   48000  4800.0

### Create a column using a condition
Suppose employees earning at least ₹50,000 are classified as "High" earners and others as "Standard".

In [98]:
df["Salary_Level"] = "Standard" # created with default and next we will change the row values not cols
print(df)

    Name  Age Department  Salary   Bonus Salary_Level
0  Rahul   25         IT   49000  4500.0     Standard
1  Priya   28         HR   54000  5000.0     Standard
2   Amit   24         IT   44000  4000.0     Standard
3   Neha   30    Finance   64000  6000.0     Standard
4  Rohan   26         HR   52000  4800.0     Standard

In [99]:
df.loc[df["Salary"] >= 50000, "Salary_Level"] = "High"
print(df)

    Name  Age Department  Salary   Bonus Salary_Level
0  Rahul   25         IT   49000  4500.0     Standard
1  Priya   28         HR   54000  5000.0         High
2   Amit   24         IT   44000  4000.0     Standard
3   Neha   30    Finance   64000  6000.0         High
4  Rohan   26         HR   52000  4800.0         High

## Modify an existing column
Suppose the company gives everyone a salary increase of ₹2,000.

In [93]:
df['Salary'] = df['Salary'] + 2000
print(df)

    Name  Age Department  Salary   Bonus
0  Rahul   25         IT   49000  4500.0
1  Priya   28         HR   54000  5000.0
2   Amit   24         IT   44000  4000.0
3   Neha   30    Finance   64000  6000.0
4  Rohan   26         HR   52000  4800.0

## Removing a column

In [48]:
df.drop('Age',axis=1)

    Name Department  Salary  Level
0  Rahul         IT   45000     12
1  Priya         HR   50000     10
2   Amit         IT   40000      3
3   Neha    Finance   60000      6
4  Rohan         HR   48000      1

Here you can see that Age is not completely removed in the below cell.

In [49]:
print(df)

    Name  Age Department  Salary  Level
0  Rahul   25         IT   45000     12
1  Priya   28         HR   50000     10
2   Amit   24         IT   40000      3
3   Neha   30    Finance   60000      6
4  Rohan   26         HR   48000      1

To remove completely, we use inplace = True

In [51]:
# df.drop('Level',axis=1,inplace=True)
# succesfully dropped the column 'Level' from the dataframe but modern way is :
df.drop(columns=['Level'], inplace=True)

C:\Users\rajib.a.poddar\AppData\Local\Temp\ipykernel_19672\2835543146.py:3: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.drop(columns=['Level'], inplace=True)

In [53]:
print(df)
# Level has been removed from the dataframe.

    Name  Age Department  Salary
0  Rahul   25         IT   45000
1  Priya   28         HR   50000
2   Amit   24         IT   40000
3   Neha   30    Finance   60000
4  Rohan   26         HR   48000

## Remove a row

In [61]:
df.drop(3,axis = 0)

    Name  Age Department  Salary
0  Rahul   25         IT   45000
1  Priya   28         HR   50000
2   Amit   24         IT   40000
4  Rohan   26         HR   48000

In [62]:
print(df)

    Name  Age Department  Salary
0  Rahul   25         IT   45000
1  Priya   28         HR   50000
2   Amit   24         IT   40000
3   Neha   30    Finance   60000
4  Rohan   26         HR   48000

## Select a row using loc and iloc

loc selects rows using their index labels.
loc basically is location.

In [65]:
print(df)

    Name  Age Department  Salary
0  Rahul   25         IT   45000
1  Priya   28         HR   50000
2   Amit   24         IT   40000
3   Neha   30    Finance   60000
4  Rohan   26         HR   48000

In [66]:
df.loc[1]

Name          Priya
Age              28
Department       HR
Salary        50000
Name: 1, dtype: object

### Select multiple rows

In [69]:
df.loc[1:3]

    Name  Age Department  Salary
1  Priya   28         HR   50000
2   Amit   24         IT   40000
3   Neha   30    Finance   60000

### You can select a particular row and column together

In [74]:
df.loc[2, "Name"]

'Amit'

In [76]:
df.loc[0:3, ["Name", "Salary"]]

    Name  Salary
0  Rahul   45000
1  Priya   50000
2   Amit   40000
3   Neha   60000

### Iloc - same as loc but for loc[2:4] both are inclusive but for iloc the ending position is excluded.

In [86]:
df.iloc[2:4]

   Name  Age Department  Salary
2  Amit   24         IT   40000
3  Neha   30    Finance   60000

Only accepts the integer position

In [88]:
df.iloc[0:3, 0:2]

    Name  Age
0  Rahul   25
1  Priya   28
2   Amit   24

## Practise Questions

### Create a new column named Tax equal to 5% of each employee's Salary.

In [106]:
df["Tax"] = df['Salary']* 0.05

### Create a column named Age_Group. Set it to 'Senior' for employees aged 28 or above, and 'Junior' for everyone else.

In [107]:
df['Age_Group'] = 'Junior'

### Increase every employee's salary by ₹3,000.

In [ ]:
df['Salary'] = df['Salary'] + 3000

### Remove the Department column and store the result back in df.

In [ ]:
df = df.drop(columns=['Department'])