# Filtering data with conditions

## Conditional Selection

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohan"],
    "Age": [25, 28, 24, 30, 26],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [45000, 50000, 40000, 60000, 48000]
}

df = pd.DataFrame(data)

### Find employees whose salary is greater than ₹45,000.

In [3]:
df[df['Salary']> 45000]

    Name  Age Department  Salary
1  Priya   28         HR   50000
3   Neha   30    Finance   60000
4  Rohan   26         HR   48000

### Find employees whose salary is greater than ₹45,000 and age is greater than 28

In [9]:
df[(df['Salary']>45000) & (df["Age"]>28)]

   Name  Age Department  Salary
3  Neha   30    Finance   60000

### Find employees who work in HR AND are older than 26.

In [11]:
df[(df['Department']=="HR") & (df["Age"]>26)]

    Name  Age Department  Salary
1  Priya   28         HR   50000

### Find employees whose salary is less than 45000 OR whose age is greater than 28.

In [12]:
df[(df['Salary']<45000) | (df["Age"]>28)]

   Name  Age Department  Salary
2  Amit   24         IT   40000
3  Neha   30    Finance   60000

### Find employees who do NOT work in IT.

In [14]:
df[(df['Department']!="IT")]

    Name  Age Department  Salary
1  Priya   28         HR   50000
3   Neha   30    Finance   60000
4  Rohan   26         HR   48000

### Find employees who work in IT AND have a salary greater than or equal to 40000.

In [ ]:
df[(df['Department']=="IT") & (df["Salary"]>=40000)]

    Name  Age Department  Salary
0  Rahul   25         IT   45000
2   Amit   24         IT   40000