# Sorting & Filtering

## Creating dataframe

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohan"],
    "Age": [25, 28, 24, 30, 26],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [45000, 50000, 40000, 60000, 48000]
}

df = pd.DataFrame(data)

In [4]:
print(df)

    Name  Age Department  Salary
0  Rahul   25         IT   45000
1  Priya   28         HR   50000
2   Amit   24         IT   40000
3   Neha   30    Finance   60000
4  Rohan   26         HR   48000

## Sorting

### Sort employees by salary

In [3]:
df.sort_values(by="Salary")

    Name  Age Department  Salary
2   Amit   24         IT   40000
0  Rahul   25         IT   45000
4  Rohan   26         HR   48000
1  Priya   28         HR   50000
3   Neha   30    Finance   60000

### Sort employees by salary DESC or highest salary first

In [5]:
df.sort_values(by="Salary", ascending=False)

    Name  Age Department  Salary
3   Neha   30    Finance   60000
1  Priya   28         HR   50000
4  Rohan   26         HR   48000
0  Rahul   25         IT   45000
2   Amit   24         IT   40000

## Filtering using isin()
It's cleaner than writing multiple equality conditions with | when checking several possible values.

### Find employees from either the IT or HR department

In [6]:
df[df['Department'].isin(['HR','IT'])]

    Name  Age Department  Salary
0  Rahul   25         IT   45000
1  Priya   28         HR   50000
2   Amit   24         IT   40000
4  Rohan   26         HR   48000

### Select employees whose department is NOT in IT or HR using isin() and ~.

In [7]:
df[~(df["Department"].isin(["IT", "HR"]))]

   Name  Age Department  Salary
3  Neha   30    Finance   60000