# Working with null values

## Create the dataframe

In [1]:
import numpy as np
import pandas as pd

In [4]:
data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohan"],
    "Age": [25, None, 24, 30, None],
    "Salary": [45000, 50000, None, 60000, 48000]
}
df = pd.DataFrame(data)

In [5]:
print(df)

    Name   Age   Salary
0  Rahul  25.0  45000.0
1  Priya   NaN  50000.0
2   Amit  24.0      NaN
3   Neha  30.0  60000.0
4  Rohan   NaN  48000.0

## Find Missing values

In [ ]:
df.isna()
# This will return a boolean DataFrame indicating which values are missing (True) or not (False).

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False
4  False   True   False

In [ ]:
df.isna().sum()
# This will return how many null values are there in each column

Name      0
Age       2
Salary    1
dtype: int64

## Fill missing values

In [ ]:
df.fillna(2)
# All the null values will be replaced with the args value eg, 2

    Name   Age   Salary
0  Rahul  25.0  45000.0
1  Priya   2.0  50000.0
2   Amit  24.0      2.0
3   Neha  30.0  60000.0
4  Rohan   2.0  48000.0

## Suppose you want to replace missing ages with 0

In [14]:
df["Age"] = df["Age"].fillna(0)
print(df)

    Name   Age   Salary
0  Rahul  25.0  45000.0
1  Priya   0.0  50000.0
2   Amit  24.0  50750.0
3   Neha  30.0  60000.0
4  Rohan   0.0  48000.0

## To replace missing salaries with the average salary

In [10]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
print(df)

    Name   Age   Salary
0  Rahul  25.0  45000.0
1  Priya   NaN  50000.0
2   Amit  24.0  50750.0
3   Neha  30.0  60000.0
4  Rohan   NaN  48000.0

## Remove rows containing missing values using dropna()
By default, this returns only rows that have no missing values in any column.

In [12]:
df.dropna()

    Name   Age   Salary
0  Rahul  25.0  45000.0
2   Amit  24.0  50750.0
3   Neha  30.0  60000.0