# Applying functions with apply()

In [1]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohan"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [45000, 50000, 40000, 60000, 48000],
    "Age": [25, 28, 24, 30, 26]
}

df = pd.DataFrame(data)
print(df)

    Name Department  Salary  Age
0  Rahul         IT   45000   25
1  Priya         HR   50000   28
2   Amit         IT   40000   24
3   Neha    Finance   60000   30
4  Rohan         HR   48000   26

## Application
### Create a column named Salary_Level: 'High' if salary is at least 50000, otherwise 'Standard'. Use a custom function with apply().

In [ ]:
def salary_level(salary):
    if salary >= 50000:
        return "High"
    else:
        return "Standard"

df["Salary_Level"] = df["Salary"].apply(salary_level)

In [3]:
df

    Name Department  Salary  Age Salary_Level
0  Rahul         IT   45000   25     Standard
1  Priya         HR   50000   28         High
2   Amit         IT   40000   24     Standard
3   Neha    Finance   60000   30         High
4  Rohan         HR   48000   26     Standard

## Use apply() and a lambda to create a column named Age_Next_Year, adding 1 to every employee's age.

In [4]:
df['Age_Next_Year'] = df['Age'].apply(lambda x: x+1)

In [5]:
df

    Name Department  Salary  Age Salary_Level  Age_Next_Year
0  Rahul         IT   45000   25     Standard             26
1  Priya         HR   50000   28         High             29
2   Amit         IT   40000   24     Standard             25
3   Neha    Finance   60000   30         High             31
4  Rohan         HR   48000   26     Standard             27

In [ ]:
df['Salary_Level'] = df['Salary'].apply(lambda x: "High" if x >= 50000 else "Standard")